#!/bin/bash
#PBS -N trimmomatic__BASE__
#PBS -o 98-logfiles/trimmomatic__BASE__.out
#PBS -l walltime=02:00:00
#PBS -l mem=60g
#PBS -l ncpus=8
#PBS -q omp
#PBS -r n

cd $PBS_O_WORKDIR


TIMESTAMP=$(date +%Y-%m-%d_%Hh%Mm%Ss)
SCRIPT=$0
NAME=$(basename $0)
LOG_FOLDER="98-logfiles"
cp $SCRIPT $LOG_FOLDER/"$TIMESTAMP"_"$NAME"

. /appli/bioinfo/trimmomatic/0.36/env.sh

# Global variables
ADAPTERFILE="/home1/datawork/jleluyer/00_ressources/univec/univec.fasta"
NCPU=8
base="__BASE__"
OUT="/home1/scratch/jleluyer/hybrids"
trimmomatic PE -Xmx60G \
        -threads 8 \
        -phred33 \
        /dataref/bioinfo/public/ifremer/pfom/gigalata/data/rna-sequence-raw/"$base"_R1.fastq.gz \
        /dataref/bioinfo/public/ifremer/pfom/gigalata/data/rna-sequence-raw/"$base"_R2.fastq.gz \
        "$OUT"/3-trimmed/"$base"_R1.paired.fastq.gz \
        "$OUT"/3-trimmed/"$base"_R1.single.fastq.gz \
        "$OUT"/3-trimmed/"$base"_R2.paired.fastq.gz \
        "$OUT"/3-trimmed/"$base"_R2.single.fastq.gz \
        ILLUMINACLIP:"$ADAPTERFILE":2:20:7 \
        LEADING:20 \
        TRAILING:20 \
        SLIDINGWINDOW:30:30 \
        MINLEN:60 2> 98-logfiles/log.trimmomatic.pe."$base"."$TIMESTAMP"   
