#!/bin/bash

# Clean up
rm 1-scripts/ase/jobs/GATK*pbs

# launch scripts for Colosse
for file in $(ls /home1/scratch/jleluyer/hybrids/5-snps/*.split.bam |grep -E "/(AA|GG)"|perl -pe 's/.split.bam//'|sort -u)

# fo testing

do
	base=$(basename "$file")
	toEval="cat 1-scripts/ase/5-variant_calling.gatk.pbs | sed 's/__BASE__/$base/g'"; eval $toEval > 1-scripts/ase/jobs/GATK_"$base".pbs
done


#change jobs header

#Submit jobs
for i in $(ls 1-scripts/ase/jobs/GATK*pbs); do qsub $i; done
